Watching for file changes with StatReloader
E:\programming_stuff\my-social-network\admin_tools\views.py changed, reloading.
Watching for file changes with StatReloader
E:\programming_stuff\my-social-network\admin_tools\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /user-management/ HTTP/1.1" 200 6492
"GET /static/css/manage_users.css HTTP/1.1" 200 625
"GET /logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 10778
"GET /static/js/save_unsave_post.js HTTP/1.1" 404 1825
"GET /register/ HTTP/1.1" 200 3581
"GET /static/css/register.css HTTP/1.1" 200 1021
"POST /register/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 17466
"GET /static/js/save_unsave_post.js HTTP/1.1" 404 1825
"GET /logout/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 10778
"GET /static/js/save_unsave_post.js HTTP/1.1" 404 1825
"GET /login/ HTTP/1.1" 200 3027
"POST /login/ HTTP/1.1" 302 0
"GET / HTTP/1.1" 200 17862
"GET /static/js/save_unsave_post.js HTTP/1.1" 404 1825
"GET /admin-dashboard/ HTTP/1.1" 200 4080
"GET /static/css/admin_dashboard.css HTTP/1.1" 304 0
"GET /user-management/ HTTP/1.1" 200 7158
"GET /static/css/manage_users.css HTTP/1.1" 304 0
"POST /delete-user/5/ HTTP/1.1" 302 0
"GET /user-management/ HTTP/1.1" 200 6492
"GET /user-management/ HTTP/1.1" 200 6492
"GET /static/css/base.css HTTP/1.1" 200 1709
"GET /static/css/hamburger_menu.css HTTP/1.1" 200 2279
"GET /static/css/manage_users.css HTTP/1.1" 200 625
"GET /static/image/search-icon.svg HTTP/1.1" 200 524
"GET /static/js/hamburger_menu.js HTTP/1.1" 200 663
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 7780
E:\programming_stuff\my-social-network\admin_tools\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user-management/
Traceback (most recent call last):
  File "E:\programming_stuff\my-social-network\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\programming_stuff\my-social-network\myvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\programming_stuff\my-social-network\myvenv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\programming_stuff\my-social-network\admin_tools\views.py", line 45, in manage_users
    return render(request, 'admin_tools/manage_users.html', {'users': users})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\programming_stuff\my-social-network\myvenv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\programming_stuff\my-social-network\myvenv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\programming_stuff\my-social-network\myvenv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: admin_tools/manage_users.html
"GET /user-management/ HTTP/1.1" 500 88453
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 7780
E:\programming_stuff\my-social-network\admin_tools\views.py changed, reloading.
Watching for file changes with StatReloader
